# To build the entire stack run 'make run'

version: '3'

services:
  tarkov_data_manager:
    container_name: tarkov_data_manager
    restart: unless-stopped
    build:
      context: ./src/tarkov-data-manager
      dockerfile: ./Dockerfile
    env_file: 
      - ./src/tarkov-data-manager/config.env
      - ./src/tarkov-data-manager/creds.env
    ports:
      - 4000:4000

  tarkov_socket_server:
    container_name: tarkov_socket_server
    restart: unless-stopped
    build:
      context: ./src/tarkov-socket-server
      dockerfile: ./Dockerfile
    depends_on:
      - tarkov_data_manager
    ports:
      - 8080:8080

  caddy:
    container_name: caddy-service
    restart: unless-stopped
    build:
      context: ./src/caddy
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    depends_on:
      - tarkov_socket_server
      - tarkov_data_manager
    environment:
      PROXY_BACKEND: tarkov_data_manager
      PROXY_PORT: 4000
      DOMAIN: ${DOMAIN}

volumes:
  caddy_data:
  caddy_config:
