name: restart-vm

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 15 * * 1-5'

jobs:
  restart-vm:
    runs-on: ubuntu-latest
    environment: production-secrets

    steps:
      - name: azure login
        uses: azure/login@de95379fe4dadc2defb305917eaa7e5dde727294 # pin@v1.5.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: restart vm
        uses: azure/CLI@b0e31ae20280d899279f14c36e877b4c6916e2d3 # pin@v1.0.8
        with:
          azcliversion: 2.50.0
          inlineScript: |
            az vm restart --resource-group tdm_rg --name tdm_vm
